name: ticket_scanner
description: A new Flutter project.

publish_to: 'none'

version: 1.1.4+7

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  mobile_scanner: ^4.0.0
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  http: ^1.2.0
  vibration: ^1.8.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartlin: ^0.6.3
  logger: ^2.0.2+1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_native_splash: ^2.3.9

dev_dependencies:
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  custom_lint: ^0.5.8
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_native_splash:
  image: assets/logo.png
  android: true
  ios: true
  color: "#1c1b20"

flutter_launcher_icons:
  android: true
  image_path: assets/logo.png
  adaptive_icon_background: "#ffffff"
