name: ticket_scanner
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0+3

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  http: ^1.1.0
  vibration: ^1.8.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartlin: ^0.6.3
  logger: ^2.0.2+1
  google_fonts: ^6.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3
  custom_lint: ^0.5.6

flutter:
  uses-material-design: true